### ISSUE TITLE
Response: invalid key supplied

### ISSUE THREAD

**Issue by scalp42** [chef/knife-push#32] opened 2015-10-13 11:14 UTC
Using `knife-push (0.9.0 3875cf2)`:

```
$> bundle exec knife job start chef -s 'chef_environment:X AND name:data-i*' --timeout  30000 --quorum 1%
ERROR: The data in your request was invalid
Response: invalid key supplied
```

Here is the verbose output:

```
DEBUG: ---- End HTTP Status/Header Data ----
DEBUG: ---- HTTP Response Body ----
DEBUG: {"error":"invalid key supplied"}
DEBUG: ---- End HTTP Response Body -----
DEBUG: ---- HTTP Request Body ----
DEBUG: {"command":"chef","nodes":["data-i-82685544"],"capture_output":false,"quorum":1,"env":{},"run_timeout":30000}
DEBUG: ---- End HTTP Request Body ----
DEBUG: Chef::HTTP calling Chef::HTTP::ValidateContentLength#handle_response
DEBUG: Content-Length validated correctly.
DEBUG: Chef::HTTP calling Chef::HTTP::RemoteRequestID#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::Authenticator#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::Decompressor#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::CookieManager#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::JSONToModelOutput#handle_response
DEBUG: Expected JSON response, but got content-type ''
DEBUG: Chef::HTTP calling Chef::HTTP::JSONInput#handle_response
INFO: HTTP Request Returned 400 Bad Request: error
/Users/scalp/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http/response.rb:119:in `error!': 400 "Bad Request" (Net::HTTPServerException)
	from /Users/scalp/.rvm/gems/ruby-2.2.1@gzbot/gems/chef-12.5.1/lib/chef/http.rb:145:in `request'
	from /Users/scalp/.rvm/gems/ruby-2.2.1@gzbot/gems/chef-12.5.1/lib/chef/http.rb:126:in `post'
	from /Users/scalp/.rvm/gems/ruby-2.2.1@gzbot/bundler/gems/knife-push-3875cf29c77c/lib/chef/knife/job_helpers.rb:96:in `run_helper'
	from /Users/scalp/.rvm/gems/ruby-2.2.1@gzbot/bundler/gems/knife-push-3875cf29c77c/lib/chef/knife/job_start.rb:106:in `run'
	from /Users/scalp/.rvm/gems/ruby-2.2.1@gzbot/gems/chef-12.5.1/lib/chef/knife.rb:405:in `block in run_with_pretty_exceptions'
	from /Users/scalp/.rvm/gems/ruby-2.2.1@gzbot/gems/chef-12.5.1/lib/chef/local_mode.rb:44:in `with_server_connectivity'
	from /Users/scalp/.rvm/gems/ruby-2.2.1@gzbot/gems/chef-12.5.1/lib/chef/knife.rb:404:in `run_with_pretty_exceptions'
	from /Users/scalp/.rvm/gems/ruby-2.2.1@gzbot/gems/chef-12.5.1/lib/chef/knife.rb:203:in `run'
	from /Users/scalp/.rvm/gems/ruby-2.2.1@gzbot/gems/chef-12.5.1/lib/chef/application/knife.rb:142:in `run'
	from /Users/scalp/.rvm/gems/ruby-2.2.1@gzbot/gems/chef-12.5.1/bin/knife:25:in `<top (required)>'
	from /Users/scalp/.rvm/gems/ruby-2.2.1@gzbot/bin/knife:23:in `load'
	from /Users/scalp/.rvm/gems/ruby-2.2.1@gzbot/bin/knife:23:in `<main>'
	from /Users/scalp/.rvm/gems/ruby-2.2.1@gzbot/bin/ruby_executable_hooks:15:in `eval'
	from /Users/scalp/.rvm/gems/ruby-2.2.1@gzbot/bin/ruby_executable_hooks:15:in `<main>'
```

Works fine with `v0.5.2`. 

Any idea?

**Comment by chef09210** [comment] 2016-04-06 23:39
Still happens

**Comment by domenicomusto** [comment] 2016-04-12 12:33
anyone solved this ?

**Comment by markbnet** [comment] 2016-04-12 12:54
Resolution would be great?

**Comment by ifourmanov** [comment] 2016-04-12 16:55
In our environment that was caused because of using knife push gem 1.0.0 against older push jobs server version. Downgrading knife-push gem to 0.5.2 solved the issue

**Comment by gliptak** [comment] 2016-04-26 15:56
List of versions published: https://rubygems.org/gems/knife-push
After running
```
gem install knife-push -v 0.5.2
knife rehash
```
now ```knife job start``` works with warning
```
WARN: Chef::REST is deprecated. Please use Chef::ServerAPI, or investigate Ridley or ChefAPI. at chefdk/gem/ruby/2.1.0/gems/knife-push-0.5.2/lib/chef/knife/job_start.rb:84:in `new'
```
but ```knife job status``` fails with:
```
chefdk/gem/ruby/2.1.0/gems/knife-push-0.5.2/lib/chef/knife/job_status.rb:24:in `run': uninitialized constant Chef::REST (NameError)
```
How can I diagnose this further?
Thanks

**Comment by gliptak** [comment] 2016-04-26 20:10
This attached ```diff``` fixes the error above for v0.5.2
[rest.txt](https://github.com/chef/knife-push/files/237396/rest.txt)

**Comment by spuder** [comment] 2016-04-29 15:42
Reverting back to 0.5.2 with this patch does push jobs working.

**Comment by RayVenn** [comment] 2016-04-29 22:43
I also met this error. I think the problem is invalid keys in the request body.

I just output the job_json hash
`{"command"=>"chef-client", "nodes"=>["client"], "capture_output"=>false, "quorum"=>1, "env"=>{}}
ERROR: The data in your request was invalid
Response: invalid key supplied`
Checking the Push Jobs API, the request body only has "command" and "nodes". So what I did was remove "capture_output", "env".

**Comment by gliptak** [comment] 2016-04-30 11:57
@afiune Would you tag/release v0.5.3 if patch is submitted? Thanks

**Comment by thommay** [comment] 2016-05-05 09:16
I just merged a patch to master in #46 to support both 1.0 and 2.0 push jobs servers. I'll be doing a gem release of 1.0.1 shortly.

**Closed by thommay** 2016-05-05 09:16 UTC

**Comment by anastazya** [comment] 2016-05-05 12:30
After upgrading to 1.0.1 , i get this message :

"WARNING: Falling back to Push Jobs v1 mode."

but the jobs run fine. Is there anything else i need to upgrade ??

**Comment by thommay** [comment] 2016-05-05 14:10
@anastazya that is correct behaviour when connecting to a 1.0 server.

**Comment by anastazya** [comment] 2016-05-05 14:11
@thommay - Thank you, and great job with version 1.0.1 . Other that the warning, works great so far .

**Comment by spuder** [comment] 2016-05-05 15:04
Thanks for fixing this. 

How do you know if you have v1 or v2 push jobs server? My chef server is fully up to date, but I'm still getting the "Falling back to Push Jobs v1 mode" warning.

**Comment by thommay** [comment] 2016-05-05 15:05
2.0 hasn't been released yet, so unless you explicitly installed something or built it from source, you have 1.0. At present I'd expect almost everyone to see that warning.
